ld/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'contact.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^cn/$', 'contact.views.home', name='cn_home'),
    url(r'^en/$', 'contact.views.en_home', name='en_home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sendmail/', 'contact.views.sendmail',name = 'sendmail'),
)

urlpatterns += staticfiles_urlpatterns()

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

class OrderForm(forms.Form):
    name = forms.CharField(max_length=100)
    tel = forms.CharField()
    address = forms.Textarea()

contact/views.py
#coding:utf8
from django.shortcuts import render_to_response
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.template import RequestContext
from django.http import Http404,HttpResponse
from django.core.mail import EmailMultiAlternatives
import datetime
# Create your views here.

def home(request):
	return render_to_response('index.html',context_instance=RequestContext(request))

def en_home(request):
	return render_to_response('en_index.html',context_instance=RequestContext(request))

def sendmail(request):

	if request.method=='POST':
		s = datetime.datetime.now().strftime('%Y%m%d%H%M%S%f')
		subject = '新订单产生:'+s
		name = request.POST['name']
		tel = request.POST['tel']
		address = request.POST['address']
		html_content = render_to_string('email_template.html', {'s':s,'name':name,'tel':tel,'address':address},context_instance=RequestContext(request))
		text_content = strip_tags(html_content)
		from_email = 'i@lushizhao.me'
		msg = EmailMultiAlternatives(subject, text_content, from_email, ['lushizhao@qq.com'])
		msg.attach_alternative(html_content, "text/html")
		msg.send()
		return HttpResponse('thanks')
	else:
		return HttpResponse('error')

templates/email_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="龍达国际快递有限公司,龙达国际快递有限公司,国际快递,国际空运,邮政大包,邮政小包">
    <meta name="author" content="">

    <title>龍达国际快递有限公司,龙达国际快递有限公司,国际快递,国际空运,邮政大包,邮政小包</title>
    <link href="/static/ld/css/bootstrap.min.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div>龙达国际快递新订单产生：</div><br/>
    <table class="table table-striped" style="width:400px;padding:5px;border:1px solid #333;">
        <caption>订单编号:{{ s }}</caption>
        <thead>
        <tr>
            <th>姓名</th>
            <th>电话</th>
            <th>地址</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ name }}</td>
            <td>{{ tel }}</td>
            <td>{{ address }}</td>
        </tr>
        </tbody>
    </table>
</body>

templates/en_index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="龍达国际快递有限公司,龙达国际快递有限公司,国际快递,国际空运,邮政大包,邮政小包">
    <meta name="author" content="">

    <title>Longda Express International Express Co.,Ltd</title>

    <!-- Bootstrap Core CSS -->
    <link href="http://longda.qiniudn.com/static/ld/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="http://longda.qiniudn.com/static/ld/css/style.css" rel="stylesheet" type="text/css">   
    <!-- Custom CSS -->
    <link href="http://longda.qiniudn.com/static/ld/css/scrolling-nav.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="http://longda.qiniudn.com/static/Buttons/css/buttons.css">


</head>

<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <nav class="navbar navbar-default navbar-fixed-top" id ="navbar" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">Longda Express</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">About</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#services">Order</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#partner">Partner</a>
                    </li>
                </ul>
                <ul class="lan">
                    <li><a href="/cn/">简体中文</a></li>
                    <li><a>|</a></li>
                    <li><a href="/en/">English</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <section id="intro" class="intro-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    
                    <div class="banner" style = "height:100%'">
                        <ul>
                            <li style="background-image: url('http://longda.qiniudn.com/static/ld/images/banner1.jpg'); background-size: 100%; background-repeat:no-repeat;">
                                <div class="inner intro-inner">
                                    <h2>Longda International Express</h2>
                                    <h4>Best Team, Best Service</h4>
                                    <a href = "#services" id ="order" class="button button-rounded button-flat-caution button-large">Order Now</a>
                                </div>
                            </li>   
                        </ul>
                    </div>               
                    
                </div>
            </div>
        </div>
    </section>

    <section id="about" class="about-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="banner">
                        <ul>
                            <li style="background-image: url('http://longda.qiniudn.com/static/ld/images/banner2.jpg'); background-size: 100%; background-repeat:no-repeat;">
                                <div class="inner about-inner">
                                    <div class="content">
                                        <h1>About Us</h1>
                                        <div class="about">
                                            <ul>
                                                <li>
                                                    <span>Monopoly(Lines for special use such as Hong Kong, Taiwan,SoutheastAsia, USA, Western Europe, Eastern Europ, Middle East, South Africa)</span>
                                                </li>
                                                <li>
                                                    <span>Act for DHL, UPS, TNT, FedEx, EMS at the same time.</span>
                                                </li>
                                                <li>
                                                    <span>Business such as international,in the homeland express delivery, international air transport, ocean shipping/</span>
                                                </li>
                                                <li>
                                                    <span>The company specialixes in powder, electronics, batteries, liquid and food express. </span>
                                                </li>
                                                <br/><br/>  
                                                <li>
                                                    <span>tel：0579-85867121</span>
                                                </li>
                                                </li>
                                                                                                <li>
                                                    <span>mobile：15372926890&nbsp;&nbsp;15372926837</span>
                                                </li>
                                                <li>
                                                    <span>address：Under king three area 16 building 1-2</span>
                                                </li>
                                                <li>
                                                    <span>QQ：519676634</span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </li>   
                        </ul>
                    </div>     
                </div>
            </div>
        </div>
    </section>

    <section id="services" class="services-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="banner" style = "height:100%'">
                        <ul>
                            <li style="background-image: url('http://longda.qiniudn.com/static/ld/images/banner3.jpg'); background-size: 100%; background-repeat:no-repeat;">
                                <div class="inner service-inner">
                                    <div class="content">
                                        <h1>Order Online</h1>

                                            <form role="form" id='form' action='/sendmail/' method='post' class="form-horizontial">
                                             {% csrf_token %} 
                                              <div class="form-group">
                                                <label for="id_name">Name</label>
                                                <input type="text" class="form-control" id="id_name" name='name' placeholder="Enter your name">
                                              </div>
                                              <div class="form-group">
                                                <label for="id_tel">Tel.</label>
                                                <input type="tel" class="form-control" id="id_tel" name = 'tel' placeholder="Enter your telephone">
                                              </div>
                                              <div class="form-group">
                                                <label for="id_address">Address</label>
                                                <textarea class="form-control" id = 'id_address' name = 'address' rows="3"></textarea>
                                              </div>
                                              <div id="msg" style="display:none; margin-bottom:5px;"><span style="color:green;">Your request is processing, please wait a minute...</span></div>
                                              <button type='submit' class="button button-rounded button-flat-highlight button-large" id="submit">Submit</button>
                                            </form>
                                    </div>
                                </div>
                            </li>   
                        </ul>
                    </div>    
                </div>
            </div>
        </div>
    </section>


    <section id="partner" class="partner-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner partner-inner">
                        <h1>Partner</h1>
                        <ul>
                            <li><a href="http://www.cn.dhl.com/zh.html"><img src="http://longda.qiniudn.com/static/ld/images/logo/dhl.jpg"></a></li>
                            <li><a href="http://www.ems.com.cn/"><img src="http://longda.qiniudn.com/static/ld/images/logo/ems.jpg"></a></li>
                            <li><a href="http://www.fedex.com/cn/"><img src="http://longda.qiniudn.com/static/ld/images/logo/fedex.jpg"></a></li>
                            <li><a href="http://www.tnt.com.cn/"><img src="http://longda.qiniudn.com/static/ld/images/logo/tnt.jpg"></a></li>
                            <li><a href="http://www.ups.com/cn"><img src="http://longda.qiniudn.com/static/ld/images/logo/ups.jpg"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Core JavaScript Files -->
    <script src="http://longda.qiniudn.com/static/ld/js/jquery-1.10.2.js"></script>
    <script src="http://longda.qiniudn.com/static/ld/js/bootstrap.min.js"></script>
    <script src="http://longda.qiniudn.com/static/ld/js/jquery.easing.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="http://longda.qiniudn.com/static/ld/js/scrolling-nav.js"></script>
    <script src="http://longda.qiniudn.com/static/ld/js/unslider.js"></script>
    <script src="http://longda.qiniudn.com/static/ld/js/jquery.form.min.js"></script>
    
    <script>
    $(function() {
        var h = $('.col-lg-12:first').css("height");
        $('.inner').css("height",h);
        $('.banner').unslider();
    });
    </script>

</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="龍达国际快递有限公司,龙达国际快递有限公司,国际快递,国际空运,邮政大包,邮政小包">
    <meta name="author" content="">

    <title>龍达国际快递有限公司,龙达国际快递有限公司,国际快递,国际空运,邮政大包,邮政小包</title>

    <!-- Bootstrap Core CSS -->
    <link href="http://longda.qiniudn.com/static/ld/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="http://longda.qiniudn.com/static/ld/css/style.css" rel="stylesheet" type="text/css">   
    <!-- Custom CSS -->
    <link href="http://longda.qiniudn.com/static/ld/css/scrolling-nav.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="http://longda.qiniudn.com/static/Buttons/css/buttons.css">


</head>

<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <nav class="navbar navbar-default navbar-fixed-top" id ="navbar" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">龍达国际快递有限公司</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">关于我们</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#services">在线下单</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#partner">合作伙伴</a>
                    </li>
                </ul>
                <ul class="lan">
                    <li><a href="/cn/">简体中文</a></li>
                    <li><a>|</a></li>
                    <li><a href="/en/">English</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <section id="intro" class="intro-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    
                    <div class="banner" style = "height:100%'">
                        <ul>
                            <li style="background-image: url('http://longda.qiniudn.com/static/ld/images/banner1.jpg'); background-size: 100%; background-repeat:no-repeat;">
                                <div class="inner intro-inner">
                                    <h1>龍达国际快递</h1>
                                    <h4>一流的团队,一流的服务</h4>
                                    <a href = "#services" id ="order" class="button button-rounded button-flat-caution button-large">立即下单</a>
                                </div>
                            </li>   
                        </ul>
                    </div>               
                    
                </div>
            </div>
        </div>
    </section>

    <section id="about" class="about-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="banner">
                        <ul>
                            <li style="background-image: url('http://longda.qiniudn.com/static/ld/images/banner2.jpg'); background-size: 100%; background-repeat:no-repeat;">
                                <div class="inner about-inner">
                                    <div class="content">
                                        <h1>关于我们</h1>
                                        <div class="about">
                                            <ul>
                                                <li>
                                                    <span>专营：（香港、东南亚、美国、西欧、东欧、中东、南非等专线）</span>
                                                </li>
                                                <li>
                                                    <span>同时代理DHL、UPS、TNT、FedEx、EMS。</span>
                                                </li>
                                                <li>
                                                    <span>邮政大包、邮政小包、国际快递、国际空运、海运等业务</span>
                                                </li>
                                                <li>
                                                    <span>本公司专业从事粉末、电子、电池、液体、食品等快运</span>
                                                </li>
                                                <br/><br/>  
                                                <li>
                                                    <span>电话：0579-85867121&nbsp;&nbsp;</span>
                                                </li>
                                                                                                <li>
                                                    <span>手机：15372926890&nbsp;&nbsp;15372926837</span>
                                                </li>
                                                <li>
                                                    <span>地址：下王3区16幢1-2号</span>
                                                </li>
                                                <li>
                                                    <span>QQ：519676634</span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </li>   
                        </ul>
                    </div>     
                </div>
            </div>
        </div>
    </section>

    <section id="services" class="services-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="banner" style = "height:100%'">
                        <ul>
                            <li style="background-image: url('http://longda.qiniudn.com/static/ld/images/banner3.jpg'); background-size: 100%; background-repeat:no-repeat;">
                                <div class="inner service-inner">
                                    <div class="content">
                                        <h1>在线下单</h1>

                                            <form role="form" id='form' action='/sendmail/' method='post' class="form-horizontial">
                                             {% csrf_token %} 
                                              <div class="form-group">
                                                <label for="id_name">姓名</label>
                                                <input type="text" class="form-control" id="id_name" name='name' placeholder="输入您的姓名">
                                              </div>
                                              <div class="form-group">
                                                <label for="id_tel">电话</label>
                                                <input type="tel" class="form-control" id="id_tel" name = 'tel' placeholder="输入您的电话">
                                              </div>
                                              <div class="form-group">
                                                <label for="id_address">地址</label>
                                                <textarea class="form-control" id = 'id_address' name = 'address' rows="3"></textarea>
                                              </div>
                                              <div id="msg" style="display:none; margin-bottom:5px;"><span style="color:green;">正在处理您的请求,请稍后....</span></div>
                                              <button type='submit' class="button button-rounded button-flat-highlight button-large" id="submit">提交</button>
                                            </form>
                                    </div>
                                </div>
                            </li>   
                        </ul>
                    </div>    
                </div>
            </div>
        </div>
    </section>


    <section id="partner" class="partner-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner partner-inner">
                        <h1>合作伙伴</h1>
                        <ul>
                            <li><a><img src="http://longda.qiniudn.com/static/ld/images/logo/dhl.jpg"></a></li>
                            <li><a><img src="http://longda.qiniudn.com/static/ld/images/logo/ems.jpg"></a></li>
                            <li><a><img src="http://longda.qiniudn.com/static/ld/images/logo/fedex.jpg"></a></li>
                            <li><a><img src="http://longda.qiniudn.com/static/ld/images/logo/tnt.jpg"></a></li>
                            <li><a><img src="http://longda.qiniudn.com/static/ld/images/logo/ups.jpg"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Core JavaScript Files -->
    <script src="http://longda.qiniudn.com/static/ld/js/jquery-1.10.2.js"></script>
    <script src="http://longda.qiniudn.com/static/ld/js/bootstrap.min.js"></script>
    <script src="http://longda.qiniudn.com/static/ld/js/jquery.easing.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="http://longda.qiniudn.com/static/ld/js/scrolling-nav.js"></script>
    <script src="http://longda.qiniudn.com/static/ld/js/unslider.js"></script>
    <script src="http://longda.qiniudn.com/static/ld/js/jquery.form.min.js"></script>
    
    <script>
    $(function() {
        var h = $('.col-lg-12:first').css("height");
        $('.inner').css("height",h);
        $('.banner').unslider();
    });
    </script>

</body>

</html>